FROM ubuntu:18.04

RUN apt-get update -y
RUN apt-get upgrade -y

# Install Node.js
ENV NODE_VERSION=12.6.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN npm install

RUN mkdir ../ml && cd ../ml
RUN apt-get install python3 && apt-get install python3-pip
RUN pip3 install keras
RUN pip3 install --upgrade tensorflow

CMD ["npm", "run", "start"]
